In [ ]:
import numpy as np

In [ ]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(list)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matriz = np.array(matriz)

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[2][2]

9

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[0,2]

3

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
matriz[0:1]

array([[1, 2, 3]])

In [ ]:
matriz[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>