> https://numpy.org/doc/stable/user/basics.types.html

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype


dtype('int64')

In [ ]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype



dtype('float64')

In [ ]:
arr


array([1, 2, 3, 4])

In [ ]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([0,1,2,3,4])
arr.astype(np.bool_)

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>