In [ ]:
import numpy as np

<img src="image-20230805-215323.png" width="75%" align="" />

Las dimensiones de los datos se utilizan para describir la estructura de los conjuntos de datos en diferentes contextos.

Scalar: Un escalar es un dato que representa un único valor. En términos matemáticos, es simplemente un número, sin dirección ni magnitud. En programación, un escalar podría ser un entero, un número decimal (punto flotante) o incluso un valor booleano (verdadero o falso). 

In [ ]:
scalar = np.array(1)
print(scalar)
scalar.ndim


1


0

Vector: Un vector es una colección ordenada de valores que pueden ser escalares. En el contexto de la matemática y la programación, los vectores son una estructura unidimensional que puede contener elementos numéricos, como números enteros o decimales. Los elementos de un vector están dispuestos en una única fila o columna.

In [ ]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

Matrix: Una matriz es una estructura bidimensional de datos dispuestos en filas y columnas. Es una tabla rectangular de números o elementos organizados en una cuadrícula. Las matrices son útiles para representar relaciones entre datos y realizar operaciones matemáticas como multiplicación de matrices.

In [ ]:
matriz_bi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz_bi)
matriz_bi.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

Tensor: En términos generales, un tensor es una generalización de los conceptos de escalar, vector y matriz. Representa una colección de datos multidimensionales. Un tensor puede tener cualquier número de dimensiones, lo que significa que puede ser un escalar (0D tensor), un vector (1D tensor), una matriz (2D tensor) o un tensor con dimensiones superiores (3D, 4D, etc.).

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

<img src="image-20230805-220800.png" width="100%" align="left" />

<img src="image-20230805-220829.png" width="100%" align="" />

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
# Crear un array de una dimensión y expandir las dimensiones del array en el eje (axis) 0
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
# Imprimir el vector original y su número de dimensiones
print("Vector original:", vector)
print("Número de dimensiones del vector original:", vector.ndim)
print('')
# Utilizar np.squeeze() para eliminar dimensiones unidimensionales (longitud 1)
vector_2 = np.squeeze(vector)
# Imprimir el vector después de utilizar np.squeeze() y su número de dimensiones
print("Vector después de np.squeeze():", vector_2)
print("Número de dimensiones del vector después de np.squeeze():", vector_2.ndim)

Vector original: [[[[[[[[[[1 2 3]]]]]]]]]]
Número de dimensiones del vector original: 10

Vector después de np.squeeze(): [1 2 3]
Número de dimensiones del vector después de np.squeeze(): 1


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>