In [ ]:
import numpy as np


In [ ]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0, 20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.28796002689105205

In [ ]:
np.random.rand(4)

array([0.72526361, 0.37018521, 0.8520313 , 0.57578063])

In [ ]:
np.random.rand(4,4)

array([[0.98778108, 0.70613825, 0.66688127, 0.21930276],
       [0.84355601, 0.83242265, 0.70994988, 0.68624384],
       [0.95388749, 0.45132513, 0.50596652, 0.42669433],
       [0.46759315, 0.3990811 , 0.05988893, 0.85340188]])

In [ ]:
np.random.randint(1,15)

4

In [ ]:
random_matriz = np.random.randint(1,100, (10,10))
print(random_matriz)
random_matriz.ndim

[[65 59 81 28 25 15 80  5 79 97]
 [15 58 11 87 77 96 93 77 94 83]
 [41 17 85 48 17 45 10 77 77 96]
 [45 77  7 12 89 15 59 24  7 81]
 [41 74  3 30 44 40 69 79 74 20]
 [42 51 60 99 36 29 72 34 37 83]
 [13 42 70  2 11 68 79 31 30 30]
 [89  4 73 80 36 57 61 64 15 37]
 [44 96 35 25 77 17 19 18 33 74]
 [63 49 31 78 77 39 90 41 31 48]]


2

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>