In [ ]:
import numpy as np


In [ ]:
# Generar una matriz de números enteros aleatorios en el rango [1, 10) con forma (3, 2)
list = np.random.randint(1,10, (3,2))

# Imprimir la matriz generada
print(list)

# Obtener la forma (shape) de la matriz
list.shape


[[3 2]
 [7 2]
 [7 7]]


(3, 2)

In [ ]:
list.reshape(1,6)

array([[3, 2, 7, 2, 7, 7]])

In [ ]:
list.reshape(2,3)

array([[3, 2, 7],
       [2, 7, 7]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>