In [ ]:
import numpy as np


In [ ]:
list = np.random.randint(1,25,10)
print(list)

[ 7  7 16 24 13  6  6 23 17  7]


In [ ]:
matriz = list.reshape(2,5)
matriz


array([[ 7,  7, 16, 24, 13],
       [ 6,  6, 23, 17,  7]])

In [ ]:
list.max()

24

In [ ]:
matriz.max()

24

In [ ]:
matriz

array([[ 7,  7, 16, 24, 13],
       [ 6,  6, 23, 17,  7]])

In [ ]:
matriz.max(1)

array([24, 23])

In [ ]:
list.argmax()

3

In [ ]:
list.min()


6

In [ ]:
matriz.min()

6

In [ ]:
list.ptp()

18

In [ ]:
matriz

array([[ 7,  7, 16, 24, 13],
       [ 6,  6, 23, 17,  7]])

In [ ]:
matriz.ptp(0)

array([1, 1, 7, 7, 6])

In [ ]:
list.sort()
print(list)

[ 6  6  7  7  7 13 16 17 23 24]


In [ ]:
np.percentile(list,50)

10.0

In [ ]:
np.median(list)

10.0

In [ ]:
np.median(matriz)

10.0

In [ ]:
np.std(list)

6.711184694225007

In [ ]:
np.var(list)

45.04

In [ ]:
np.mean(list)

12.6

max(): El método max() de NumPy se utiliza para encontrar el valor máximo en un array. Si se aplica a una matriz multidimensional, se puede especificar el eje a lo largo del cual se debe encontrar el máximo.

min(): El método min() de NumPy se utiliza para encontrar el valor mínimo en un array. Al igual que max(), si se aplica a una matriz multidimensional, se puede especificar el eje para encontrar el mínimo a lo largo de una dimensión específica.

argmax(): El método argmax() de NumPy se utiliza para encontrar el índice del valor máximo en un array. Devuelve el índice del primer elemento que tenga el valor máximo. Si se aplica a una matriz multidimensional, se puede especificar el eje para encontrar el índice máximo a lo largo de una dimensión específica.

argmin(): El método argmin() de NumPy se utiliza para encontrar el índice del valor mínimo en un array. Devuelve el índice del primer elemento que tenga el valor mínimo. Si se aplica a una matriz multidimensional, se puede especificar el eje para encontrar el índice mínimo a lo largo de una dimensión específica.

En resumen, max() y min() encuentran los valores máximo y mínimo en un array, mientras que argmax() y argmin() encuentran los índices de los valores máximo y mínimo en un array, respectivamente. Estos métodos son muy útiles en análisis de datos y operaciones numéricas en NumPy.

In [ ]:
a = np.array([[1,2], [3,4]])
print(a)
b = np.array([5,6])
print(b)


[[1 2]
 [3 4]]
[5 6]


In [ ]:
print(a.ndim)
print(b.ndim)


2
1


In [ ]:
b = np.expand_dims(b, axis=0)

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
b

array([[5, 6]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>