In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_arr = arr[0:6]

In [ ]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_arr[:] = 0

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

El método copy() en NumPy se utiliza para crear una copia independiente de un array. Al realizar una copia con copy(), se crea una nueva instancia del array con los mismos datos, pero cualquier cambio realizado en la copia no afectará al array original y viceversa. Es decir, la copia y el original son arrays distintos en memoria.

In [ ]:
import numpy as np

# Crear un array
original = np.array([1, 2, 3, 4, 5])

# Crear una copia del array
copia = original.copy()

# Modificar la copia
copia[0] = 10

print(original)
print(copia)

[1 2 3 4 5]
[10  2  3  4  5]


En este ejemplo, hemos creado un array original. Luego, usamos original.copy() para crear una copia independiente llamada copia. Después, modificamos el primer elemento de copia, pero el array original no se ve afectado por este cambio.

El método copy() es especialmente útil cuando se necesita trabajar con una versión modificada del array sin alterar el original o para evitar comportamientos inesperados cuando se manipulan arrays en funciones y subrutinas.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>