In [ ]:
import numpy as np


In [ ]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
index_cond = arr > 5
index_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
print(arr[index_cond])

[ 6  7  8  9 10]


In [ ]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [ ]:
matriz = np.random.randint(1, 100, (3,6))

In [ ]:
matriz

array([[90, 93, 76, 26, 28, 79],
       [13, 51, 11, 42, 55, 37],
       [44, 90, 85, 15, 55, 47]])

In [ ]:
new_matriz = matriz[0]
if new_matriz.min() > 30:
    print(f"El numero minimo es mayor a 30")
else:
    print("El numero minimo es menor a 30")

El numero minimo es menor a 30


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6f762273-08b7-49e6-9f67-2f78a3f4f391' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>